/*
 * GPIO_CONFIG.c
 *
 *  Created on: Aug 12, 2022
 *      Author: youssef
 */
#include "STD_TYPES.h"
#include "BIT_MATH.h"
#include "GPIO_config.h"
#include "GPIO_interface.h"
/*ARRAY_OF_PINS[NUMBER_OF_USED_PINS]={
		{PORT ,PIN ,MODE ,TYPE ,SPEED , INPUT_PULL_UP_DOWN, AF_MODE}}*/

pinInfo ARRAY_OF_PINS[NUMBER_OF_USED_PINS]={
		{PORT_A,PIN_5,AF,NOT_USED,NOT_USED,FLOATING,AF_5_SPI1_2_4},
		{PORT_A,PIN_6,AF,NOT_USED,NOT_USED,FLOATING,AF_5_SPI1_2_4},
		{PORT_A,PIN_7,AF,NOT_USED,NOT_USED,FLOATING,AF_5_SPI1_2_4},
		{PORT_A,PIN_0,OUTPUT,PUSH_PULL,MEDIUM_SPEED,NOT_USED,NOT_USED},
		{PORT_A,PIN_1,OUTPUT,PUSH_PULL,MEDIUM_SPEED,NOT_USED,NOT_USED},
		{PORT_A,PIN_9,OUTPUT,PUSH_PULL,MEDIUM_SPEED,NOT_USED,NOT_USED}

};


